name: "Bug report"
description: "Create a report to help us improve"
title: ""
labels: ["bug"]
assignees: []
body:
  - type: input
    id: parentKey
    attributes:
      label: 'Task Ticket Number'
      value: |
        MODU-0
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: 'Describe the bug'
      description: 'A clear and concise description of what the bug is.'
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 'To Reproduce'
      description: "Steps to reproduce the behavior:\n1. Go to '...'\n2. Click on '...'\n3. Scroll down to '...'\n4. See error."
    validations:
      required: true
      
  - type: textarea
    id: details
    attributes:
      label: 'Expected behavior'
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '체크리스트(Tasks)'
      description: '해당 이슈에 대해 필요한 작업 목록을 작성해주세요'
      value: |
        -[ ] Task1
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: '참조(References)'
      description: '해당 이슈과 관련된 레퍼런스를 참조해주세요'
      value: |
        - Reference1
    validations:
      required: false
