name: "Bug report"
description: "Create a report to help us improve"
title: "title"
labels: ["bug"]
assignees: []
body:
  - type: input
    id: parentKey
    attributes:
      label: 'Task Ticket Number'
      value: |
        MODU-0
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: 'Describe the bug'
      description: 'A clear and concise description of what the bug is.'
    validations:
      required: true

  - type: textarea
    id: to-reproduce
    attributes:
      label: 'To Reproduce'
      description: "Steps to reproduce the behavior:"
      placeholder: "\n1. Go to '...'\n2. Click on '...'\n3. Scroll down to '...'\n4. See error."
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: 'Expected behavior'
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: file
    id: screenshots
    attributes:
      label: 'Screenshots'
      description: 'If applicable, add screenshots to help explain your problem.'
    validations:
      required: false

  - type: textarea
    id: desktop
    attributes:
      label: 'Desktop'
      description: 'please complete the following information'
      value: |
         - OS: [e.g. iOS]
         - Browser [e.g. chrome, safari]
         - Version [e.g. 22]
    validations:
      required: false

  - type: textarea
    id: smartphone
    attributes:
      label: 'Smartphone'
      description: 'please complete the following information'
      value: | 
        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS8.1]
        - Browser [e.g. stock browser, safari]
        - Version [e.g. 22]
    validations:
      required: false

      
    - type: textarea
      id: additional-context
      attributes:
        label: 'Additional context'
        description: 'Add any other context about the problem here.'
      validations:
        required: false
