name: 'Custom issue template'
description: "Describe this issue template's purpose here."
labels: []
title: 'title'
body:
  - type: input
    id: parentKey
    attributes:
      label: 'Task Ticket Number'
      value: |
        MODU-1
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 'Description'
    validations:
      required: true
